# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotDetection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotDetection.proto',
  package='insight_msgs',
  serialized_pb=_b('\n\x14RobotDetection.proto\x12\x0cinsight_msgs\"Z\n\x0eRobotDetection\x12\x0f\n\x07\x62\x65\x61ring\x18\x01 \x02(\x01\x12\r\n\x05range\x18\x02 \x02(\x01\x12\x0b\n\x03red\x18\x03 \x01(\x05\x12\r\n\x05green\x18\x04 \x01(\x05\x12\x0c\n\x04\x62lue\x18\x05 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROBOTDETECTION = _descriptor.Descriptor(
  name='RobotDetection',
  full_name='insight_msgs.RobotDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bearing', full_name='insight_msgs.RobotDetection.bearing', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='insight_msgs.RobotDetection.range', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='red', full_name='insight_msgs.RobotDetection.red', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='green', full_name='insight_msgs.RobotDetection.green', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blue', full_name='insight_msgs.RobotDetection.blue', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['RobotDetection'] = _ROBOTDETECTION

RobotDetection = _reflection.GeneratedProtocolMessageType('RobotDetection', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTDETECTION,
  __module__ = 'RobotDetection_pb2'
  # @@protoc_insertion_point(class_scope:insight_msgs.RobotDetection)
  ))
_sym_db.RegisterMessage(RobotDetection)


# @@protoc_insertion_point(module_scope)
