# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TextMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TextMessage.proto',
  package='insight_msgs',
  serialized_pb=_b('\n\x11TextMessage.proto\x12\x0cinsight_msgs\"v\n\x0bTextMessage\x12\x16\n\x0esending_module\x18\x01 \x02(\t\x12\x16\n\x0eseverity_level\x18\x02 \x02(\t\x12\x0f\n\x07message\x18\x03 \x02(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\x12\x13\n\x0bline_number\x18\x05 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TEXTMESSAGE = _descriptor.Descriptor(
  name='TextMessage',
  full_name='insight_msgs.TextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sending_module', full_name='insight_msgs.TextMessage.sending_module', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='severity_level', full_name='insight_msgs.TextMessage.severity_level', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='insight_msgs.TextMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='insight_msgs.TextMessage.file_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='line_number', full_name='insight_msgs.TextMessage.line_number', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['TextMessage'] = _TEXTMESSAGE

TextMessage = _reflection.GeneratedProtocolMessageType('TextMessage', (_message.Message,), dict(
  DESCRIPTOR = _TEXTMESSAGE,
  __module__ = 'TextMessage_pb2'
  # @@protoc_insertion_point(class_scope:insight_msgs.TextMessage)
  ))
_sym_db.RegisterMessage(TextMessage)


# @@protoc_insertion_point(module_scope)
