# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InsightMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RobotBatteryStatus_pb2
import RobotDetection_pb2
import RobotPos_pb2
import RobotPose_pb2
import TextMessage_pb2
import Variable_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='InsightMsg.proto',
  package='insight_msgs',
  serialized_pb=_b('\n\x10InsightMsg.proto\x12\x0cinsight_msgs\x1a\x18RobotBatteryStatus.proto\x1a\x14RobotDetection.proto\x1a\x0eRobotPos.proto\x1a\x0fRobotPose.proto\x1a\x11TextMessage.proto\x1a\x0eVariable.proto\"\xd5\x03\n\nInsightMsg\x12\x12\n\nrobot_name\x18\x01 \x02(\t\x12\x37\n\x08msg_type\x18\x02 \x02(\x0e\x32%.insight_msgs.InsightMsg.Message_Type\x12:\n\x0e\x62\x61ttery_status\x18\x65 \x01(\x0b\x32 .insight_msgs.RobotBatteryStatusH\x00\x12\x31\n\tdetection\x18\x66 \x01(\x0b\x32\x1c.insight_msgs.RobotDetectionH\x00\x12*\n\x08position\x18g \x01(\x0b\x32\x16.insight_msgs.RobotPosH\x00\x12\'\n\x04pose\x18h \x01(\x0b\x32\x17.insight_msgs.RobotPoseH\x00\x12,\n\x07txt_msg\x18i \x01(\x0b\x32\x19.insight_msgs.TextMessageH\x00\x12)\n\x07var_msg\x18j \x01(\x0b\x32\x16.insight_msgs.VariableH\x00\"U\n\x0cMessage_Type\x12\x0b\n\x07\x42\x41TTERY\x10\x01\x12\r\n\tDETECTION\x10\x02\x12\x07\n\x03POS\x10\x03\x12\x08\n\x04POSE\x10\x04\x12\x08\n\x04TEXT\x10\x05\x12\x0c\n\x08VARIABLE\x10\x06\x42\x06\n\x04\x62ody')
  ,
  dependencies=[RobotBatteryStatus_pb2.DESCRIPTOR,RobotDetection_pb2.DESCRIPTOR,RobotPos_pb2.DESCRIPTOR,RobotPose_pb2.DESCRIPTOR,TextMessage_pb2.DESCRIPTOR,Variable_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_INSIGHTMSG_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Message_Type',
  full_name='insight_msgs.InsightMsg.Message_Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BATTERY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DETECTION', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POS', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VARIABLE', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=527,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_INSIGHTMSG_MESSAGE_TYPE)


_INSIGHTMSG = _descriptor.Descriptor(
  name='InsightMsg',
  full_name='insight_msgs.InsightMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_name', full_name='insight_msgs.InsightMsg.robot_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='insight_msgs.InsightMsg.msg_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_status', full_name='insight_msgs.InsightMsg.battery_status', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detection', full_name='insight_msgs.InsightMsg.detection', index=3,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='insight_msgs.InsightMsg.position', index=4,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='insight_msgs.InsightMsg.pose', index=5,
      number=104, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='txt_msg', full_name='insight_msgs.InsightMsg.txt_msg', index=6,
      number=105, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var_msg', full_name='insight_msgs.InsightMsg.var_msg', index=7,
      number=106, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSIGHTMSG_MESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='body', full_name='insight_msgs.InsightMsg.body',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=151,
  serialized_end=620,
)

_INSIGHTMSG.fields_by_name['msg_type'].enum_type = _INSIGHTMSG_MESSAGE_TYPE
_INSIGHTMSG.fields_by_name['battery_status'].message_type = RobotBatteryStatus_pb2._ROBOTBATTERYSTATUS
_INSIGHTMSG.fields_by_name['detection'].message_type = RobotDetection_pb2._ROBOTDETECTION
_INSIGHTMSG.fields_by_name['position'].message_type = RobotPos_pb2._ROBOTPOS
_INSIGHTMSG.fields_by_name['pose'].message_type = RobotPose_pb2._ROBOTPOSE
_INSIGHTMSG.fields_by_name['txt_msg'].message_type = TextMessage_pb2._TEXTMESSAGE
_INSIGHTMSG.fields_by_name['var_msg'].message_type = Variable_pb2._VARIABLE
_INSIGHTMSG_MESSAGE_TYPE.containing_type = _INSIGHTMSG
_INSIGHTMSG.oneofs_by_name['body'].fields.append(
  _INSIGHTMSG.fields_by_name['battery_status'])
_INSIGHTMSG.fields_by_name['battery_status'].containing_oneof = _INSIGHTMSG.oneofs_by_name['body']
_INSIGHTMSG.oneofs_by_name['body'].fields.append(
  _INSIGHTMSG.fields_by_name['detection'])
_INSIGHTMSG.fields_by_name['detection'].containing_oneof = _INSIGHTMSG.oneofs_by_name['body']
_INSIGHTMSG.oneofs_by_name['body'].fields.append(
  _INSIGHTMSG.fields_by_name['position'])
_INSIGHTMSG.fields_by_name['position'].containing_oneof = _INSIGHTMSG.oneofs_by_name['body']
_INSIGHTMSG.oneofs_by_name['body'].fields.append(
  _INSIGHTMSG.fields_by_name['pose'])
_INSIGHTMSG.fields_by_name['pose'].containing_oneof = _INSIGHTMSG.oneofs_by_name['body']
_INSIGHTMSG.oneofs_by_name['body'].fields.append(
  _INSIGHTMSG.fields_by_name['txt_msg'])
_INSIGHTMSG.fields_by_name['txt_msg'].containing_oneof = _INSIGHTMSG.oneofs_by_name['body']
_INSIGHTMSG.oneofs_by_name['body'].fields.append(
  _INSIGHTMSG.fields_by_name['var_msg'])
_INSIGHTMSG.fields_by_name['var_msg'].containing_oneof = _INSIGHTMSG.oneofs_by_name['body']
DESCRIPTOR.message_types_by_name['InsightMsg'] = _INSIGHTMSG

InsightMsg = _reflection.GeneratedProtocolMessageType('InsightMsg', (_message.Message,), dict(
  DESCRIPTOR = _INSIGHTMSG,
  __module__ = 'InsightMsg_pb2'
  # @@protoc_insertion_point(class_scope:insight_msgs.InsightMsg)
  ))
_sym_db.RegisterMessage(InsightMsg)


# @@protoc_insertion_point(module_scope)
