# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotBatteryStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotBatteryStatus.proto',
  package='insight_msgs',
  serialized_pb=_b('\n\x18RobotBatteryStatus.proto\x12\x0cinsight_msgs\"+\n\x12RobotBatteryStatus\x12\x15\n\rbattery_level\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROBOTBATTERYSTATUS = _descriptor.Descriptor(
  name='RobotBatteryStatus',
  full_name='insight_msgs.RobotBatteryStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='battery_level', full_name='insight_msgs.RobotBatteryStatus.battery_level', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['RobotBatteryStatus'] = _ROBOTBATTERYSTATUS

RobotBatteryStatus = _reflection.GeneratedProtocolMessageType('RobotBatteryStatus', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTBATTERYSTATUS,
  __module__ = 'RobotBatteryStatus_pb2'
  # @@protoc_insertion_point(class_scope:insight_msgs.RobotBatteryStatus)
  ))
_sym_db.RegisterMessage(RobotBatteryStatus)


# @@protoc_insertion_point(module_scope)
