# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotPose.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotPose.proto',
  package='insight_msgs',
  serialized_pb=_b('\n\x0fRobotPose.proto\x12\x0cinsight_msgs\"5\n\tRobotPose\x12\x0c\n\x04roll\x18\x01 \x02(\x01\x12\r\n\x05pitch\x18\x02 \x02(\x01\x12\x0b\n\x03yaw\x18\x03 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROBOTPOSE = _descriptor.Descriptor(
  name='RobotPose',
  full_name='insight_msgs.RobotPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='insight_msgs.RobotPose.roll', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='insight_msgs.RobotPose.pitch', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='insight_msgs.RobotPose.yaw', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['RobotPose'] = _ROBOTPOSE

RobotPose = _reflection.GeneratedProtocolMessageType('RobotPose', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTPOSE,
  __module__ = 'RobotPose_pb2'
  # @@protoc_insertion_point(class_scope:insight_msgs.RobotPose)
  ))
_sym_db.RegisterMessage(RobotPose)


# @@protoc_insertion_point(module_scope)
